List<String> mylist = [
  'Web Development',
  'App Development',
  'Interet Of Things',
  'Cyber Security',
  'Data Science',
  '    Software\nDevelopment',
  'UI/UX Design',
  'Digital Marketing',
  'Content Writing',
  'Digital Media\n   Promoter',
  'Process Associate',
  'HR',
  "Full Stack Dev",
  'Business Development\n              Associate',
  'Business Development Associate',
];
List<String> domainList = [
  'Web Development',
  'App Development',
  'Interet Of Things',
  'Cyber Security',
  'Data Science',
  'Software Development',
  'UI/UX Design',
  'Digital Marketing',
  'Content Writing',
  'Digital Media Promoter',
  'Process Associate',
  'HR',
  "Full Stack Dev",
  'Business Development\nAssociate',
  'Business Development Associate',
];

List<String> myimages = [
  'images/webdevlopment.jpg',
  'images/andri.jpg',
  'images/iot.jpg',
  'images/cs.jpg',
  'images/automl.jpg',
  'images/sd.jpg',
  'images/uiux.jpg',
  'images/dm.jpg',
  'images/t.jpg',
  'images/digprom.jpg',
  'images/t.jpg',
  'images/hr.jpg',
  'images/fstd.jpg',
  'images/t.jpg',
  'images/t.jpg',
];
