var contents = {
  '0':
      '“Design and Develop Website Mass-Mail Dispatcher” \n1. The system have been working with in this project is the web-based Mass-Mail Dispatcher.\n2. The application is designed to send mass mails to all the recipients uploaded through a CSV file. \n3. The purpose of this is to provide a tool to control and send emails to a vast number of recipients.\n4. The application will list and sort out all the valid and invalid emails detected by the application allowing the users to more readily send emails as per user convenience. \n5. The end user should be able to upload CSV file. \n6. The application shall list the detected invalid emails found in the CSV File. \n7. The user should be given a structured list of the valid emails.',
  '1':
      'Let’s assume students want to apply Exposys Data Labs Virtual internship through mobile application. \n1. Create Mobile User Interface.\n2. Develop Registration form & Login Credential.\n3. Explore different domains with ICONS.\n4. You can select the domain from the menu.\n5. You can apply\n6. YOU CAN BUILD THIS APP USING ANDROID STUDIO.',
  '2':
      'Develop Intelligent Traffic information System based on Internet of things:\n1. It connected to internet to receive data from traffic center or transmit data to car.\n2. Or it can store data the car take an action according to the received data.',
  '3':
      'Encryption and Decryption of Text By Using Caesar Cipher. Explanation: For example, if you encrypt the word ‘Software’ by shifting 3 alphabets, then the Caesar chipper for it will be ‘VRIWZDUH.’ So, you can start by building a Software Interface to break such simple encryption; later on, you can move on to complex concepts. Your software interface should have a space for the input text, and drop option to choose the ‘Shift,’ and a space for the output text, which will be the cipher decoded text. \nDevelop Caesar Cipher method using any programming language.',
  '4':
      'In the given dataset, R&D Spend, Administration Cost and Marketing Spend of 50 Companies are given along with the profit earned. The target is to prepare an ML model which can predict the profit value of a company if the value of its R&D Spend, Administration Cost and Marketing Spend are given.\n i) Construct Different Regression algorithms.\n ii) Divide the data into train set and test set.\n iii) Calculate different regression metrics.\n iv) Choose the best model\n Language: Python or R\n DATA SET LINK:\n',
  '5':
      'Building an E-Learning Web application Platform guides you through creating an e-learning platform. You will add fixtures to your project, use model inheritance, create custom model fields, use class-based views, and manage groups and permissions. You will create a content management system and handle formsets.',
  '6':
      '1. Design the poster that helps you to promote company products or Services.\n2. Use case: Design Exposys Data Labs Virtual Internship Posters With different domains with attractive contents.\n3. Domains Like Data Science,FrontEnd Developer,BackEnd Developer Full Stack Developer UI/UX Design Etc.',
  '7':
      '1. Work on Social media marketing generate leads for Exposys Data Labs Virtual Internship\n2. Report your leads in the form of Excel sheet and send datalabs491@gmail.com\n3. Work on Email Marketing and Write Content about Exposys Data Labs Virtual Internship.\n4. Make Reports\n5. Work on Designs related services\n6. Create short ads.',
  '8':
      '1. Crate Content for company Services/Products\n2. Write all contents in the document\n3. Use Case1: You Can Create Content about Exposys Data Labs Virtual Internship FAQ\n4. Use Case2: You can create Content about Exposys Data Labs Services',
  '9':
      '1. Monitor all Social Media\n2. Work on Branding\n3. Make Daily Report about Social Media Followers\nUSE CASE:\nHow to promote Company Links Like Follow,Share. Youtube Channels and Subscribe throughPan India/World Wide Using own Strategies. Examples the following Links can be Use user Own digital media promotion Strategies.\n 2. Come with Solution all Digital media promotion and channels and increase the followers on YouTube,Instagram,Pinterest,Twitter,LinkedIn,Facebook. \n LINK TO ALL PROFILES IS GIVEN IN ABOUT US PAGE',
  '10':
      '1. Understand company services or product\n2. Depth understand about process of Services\n3. Explain clearly about Services\n4. Work on customer Services',
  '11':
      '1. Collect pan India Engineering College details which includes total 28 states.\n2. Make a table with S.no , College Name , Principal Name and Email, TPO name and email.\n3. Work on Company Requirement\n4. Work on Hiring/on boarding/Screening/Negotiation Etc',
  '12':
      'Students build a complete Full Stack web application. They will work on project selection, requirements gathering, project implementation and presentation.\nGlimpse of FrontEnd Lab/Project:\nObjective:\nBrrrgrrr - A online website that sells burgers. It suggests users to not only customize their burgers by adding or removing ingredients but also create their own burger from the ingredients in stock.\nMandatory things:\n1. Arrays\n2. DOM Manipulation\n3. ES6 compatible\n4. Higher Order Functions\nGlimpse of BackEnd Lab/Project:\nObjective\nBlog Application - Build a blog application end to end with modules such as login, sign up, new post addition deletion updation, search etc.\nMandatory things:\n1. CRUD operations\n2. File saving using Excel/Word\n3. OOPs concepts',
  '13':
      '1. Build contacts with potential clients to create new business opportunities\n2. Keep prospective client database updated\n3. Make cold calls for new business leads\n4. Support in writing new business proposals\n5. Maintain knowledge of all product and service offerings of the company\n6. Arrange meetings for senior management with prospective clients\n7. Follow company guidelines and procedures for acquisition of customers, submission of tenders etc.',
  '15':
      'PROJECT DESCRIPTION/nIn the given dataset, R&D Spend, Administration Cost and Marketing Spend of 50 Companies are given along with the profit earned. The target is to prepare an ML model which can predict the profit value of a company if the value of its R&D Spend, Administration Cost and Marketing Spend are given.\n i) Construct Different Regression algorithms.\n ii) Divide the data into train set and test set.\n iii) Calculate different regression metrics.\n iv) Choose the best model\n Language: Python or R\n DATA SET LINK:\n',
};
